### ISSUE TITLE
Failing to replicate the right result

### ISSUE THREAD

**Issue by HJL8055** [qinche106/cb-convlstm-eyetracking#6]
Hello,
### But after training 60 epochs, I get a bad result.
Size 60, Epoch 59, Loss: 0.007099685608409345, err_rate_1:0.9864583611488342, err_rate_3:0.8781250715255737, err_rate_5:0.6864583492279053  err: 0.33020836114883423 num_values: 317 tot_values: 960
![event_plot_59](https://github.com/qinche106/cb-convlstm-eyetracking/assets/66299911/296c8ac6-c126-4611-a4fe-d736fa0c22a4)
I appreciate any assistance or insights into resolving this issue. Thank you in advance!

**Comment by ZuowenWang0000** [comment]
Hello,
Could you please re-download the dataset and also pull the code again and try again?
We uploaded a validation file with the wrong stride, which caused a mismatch with the ground truth. It should be fixed now. Please be aware in these plots, there are two recordings, each with 480 data points. 

Sorry for causing the inconvenience!

**Comment by HJL8055** [comment]
> Hello, Could you please re-download the dataset and also pull the code again and try again? We uploaded a validation file with the wrong stride, which caused a mismatch with the ground truth. It should be fixed now. Please be aware in these plots, there are two recordings, each with 480 data points.
> 
> Sorry for causing the inconvenience!

Wow, it worked for me! Thank you very much!
![event_plot_84](https://github.com/qinche106/cb-convlstm-eyetracking/assets/66299911/3c134332-f90c-472e-92ae-59eca8248309)
