### ISSUE TITLE
The problem of data

### ISSUE THREAD

**Issue by songsishun** [qinche106/cb-convlstm-eyetracking#8]
您好，我前些天拜读了您的这篇论文。去下载了您的开源数据集是.h5文件。但是我无法用python和HDF等软件读取您的文件内容。能告诉我原因嘛！这是我的邮箱songsishun23@mails.ucas.ac.cn。

**Comment by ZuowenWang0000** [comment]
Dear songsishun,
Please refer to 

1. the dataset class https://github.com/qinche106/cb-convlstm-eyetracking/blob/3et_real/eyetracking-convlstm/3et_real_dataset.py
2. main training script https://github.com/qinche106/cb-convlstm-eyetracking/blob/3et_real/eyetracking-convlstm/convlstm-et-pytorch-event.py

Thanks for your inquiry!
best,
zw
